# Name(s)
**Lindsey Henry**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

What are some examples of magic commands and why would you use them? Which ones will be the most useful for this course? 


## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [8]:
import numpy as np
a = np.full((6,4), 2)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 2

In [9]:
b = np.full((6,4),1)
np.fill_diagonal(b, 3)
b

array([[3, 1, 1, 1],
       [1, 3, 1, 1],
       [1, 1, 3, 1],
       [1, 1, 1, 3],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Exercise 3

a * b multiplies the elements of the same index from each numpy array and requires the arrays be the same size. This works because a and b are the same size. 
np.dot(a,b) takes the dot product of the two matrices which requires matrix a to have the same number of columns as b has rows, these dimensions do not match so mathematically it does not work. 

## Exercise 4

The result of matrix multiplication is always the outer dimensions of the matrices being multiplied.

## Exercise 5

In [21]:
def printingFunc():
    print("Something")
printingFunc()

Something


## Exercise 6

In [33]:
def randomStats():
    a = np.random.random_sample((1,5)) 
    print(a)
    print("sum: " + str(np.sum(a)))
    print("mean: " + str(np.mean(a)))
    print("")
    
randomStats()
randomStats()
randomStats()



[[0.6228158  0.63352937 0.91837123 0.99721662 0.84031233]]
sum: 4.012245355344924
mean: 0.8024490710689849

[[0.54107488 0.59995893 0.05713392 0.74238828 0.3936676 ]]
sum: 2.334223623432141
mean: 0.46684472468642824

[[0.00750612 0.38084334 0.53850606 0.89504386 0.56657447]]
sum: 2.388473845316653
mean: 0.4776947690633306



## Exercise 7

In [47]:
#Write a function that consists of a set of loops that run through an array
#and count the number of ones in it. Do the same thing using the where() function
#(use info(where) to find out how to use it).

c = np.full((2,5), 1)

def numOnesLoop(a):
    a = a.flat
    count = 0
    for i in a:
        if i == 1:
            count += 1
    return count

print(numOnes(c))


def numOnesWhere(a):
    returnnp.where(a == 1, a)

numOnesWhere(c)

10


25

## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE